apiVersion: v1
kind: Service
metadata:
  labels:
    app: sardis
  name: sardis-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: sardis
  type: LoadBalancer
