apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sardis-fe
  name: sardis-fe-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sardis-fe
  template:
    metadata:
      labels:
        app: sardis-fe
    spec:
      containers:
      - image: benjamindckr/sardis-fe:latest
        name: sardis-fe
        # env:     # not needed anymore bc backend URL will be set in config.js file
        # - name: SARDIS_BACKEND_IP
        #   value: 0.0.0.0
        ports:
        - containerPort: 3000