apiVersion: v1
kind: Service
metadata:
  labels:
    app: sardis-fe
  name: sardis-fe-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: sardis-fe
  type: LoadBalancer