apiVersion: v1
kind: Service
metadata:
  labels:
    app: sardis-be
  name: sardis-be-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sardis-be
  type: LoadBalancer