name: CI/CD Pipeline

on: 
  push: 
    branches: 
      - main 

jobs: 
  pushonmain: 
    runs-on: ubuntu-latest 
    steps: 
      - run: |
          echo "-------starting-------"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: front_end
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ghactionstest1:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/ghactionstest1:${{ github.run_number }}
      - run: |
          echo "-------done-------"

