name: front end CI Pipeline

on: 
  push: 
    branches: 
      - main
    paths:
      - 'front_end/**'

jobs: 
  build-and-push-image: 
    runs-on: ubuntu-latest 
    steps: 
      - run: |
          echo "-------starting-------"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: front_end
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sardis-fe:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/sardis-fe:${{ github.run_number }}
      - run: |
          echo "-------done-------"

